import {
  create,
  NAlert,
  NBadge,
  NButton,
  NCard,
  NConfigProvider,
  NDialogProvider,
  NDivider,
  NDropdown,
  NEmpty,
  NForm,
  NFormItem,
  NGradientText,
  NIcon,
  NInput,
  NInputNumber,
  NLayout,
  NLayoutContent,
  NLayoutHeader,
  NLayoutSider,
  NList,
  NListItem,
  NMessageProvider,
  NModal,
  NNotificationProvider,
  NProgress,
  NRadioGroup,
  NRadioButton,
  NSelect,
  NSkeleton,
  NSpin,
  NStatistic,
  NSteps,
  NStep,
  NSwitch,
  NTag,
  NTimePicker,
  NTimeline,
  NTimelineItem,
  NTooltip,
} from 'naive-ui'
import { lightThemeOverrides } from '@/styles/theme'

// naive 对象集中注册项目中会用到的 Naive UI 组件，减少重复引用。
export const naive = create({
  components: [
    NAlert,
    NBadge,
    NButton,
    NCard,
    NConfigProvider,
    NDialogProvider,
    NDivider,
    NDropdown,
    NEmpty,
    NForm,
    NFormItem,
    NGradientText,
    NIcon,
    NInput,
    NInputNumber,
    NLayout,
    NLayoutContent,
    NLayoutHeader,
    NLayoutSider,
    NList,
    NListItem,
    NMessageProvider,
    NModal,
    NNotificationProvider,
    NProgress,
    NRadioGroup,
    NRadioButton,
  NSelect,
  NSkeleton,
  NSpin,
  NStatistic,
  NSteps,
  NStep,
  NSwitch,
  NTag,
    NTimePicker,
    NTimeline,
    NTimelineItem,
    NTooltip,
  ],
})

// themeOverrides 暴露统一的主题覆写，供 NConfigProvider 使用。
export const themeOverrides = lightThemeOverrides
